FROM python

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Define the command to run when the container starts
# In this case, it will run "python bmi.py"
CMD ["python", "bmi.py"]

